<<<<<<< HEAD
# Generated by Django 4.1 on 2022-11-05 04:07
=======
# Generated by Django 4.1.3 on 2022-11-09 08:03
>>>>>>> backupFriday

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroAsociado', '0013_remove_catalogoreferencias_cliente_idcliente1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='actaAsociado',
            fields=[
                ('idActaAsociado', models.AutoField(primary_key=True, serialize=False)),
                ('firmaPresidente', models.CharField(max_length=100)),
                ('firmaSecretaria', models.CharField(max_length=100)),
                ('numActa', models.IntegerField()),
                ('fechaActa', models.DateField()),
            ],
            options={
                'db_table': 'actaAsociado',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='asociacion',
            name='estadoAsociacion',
<<<<<<< HEAD
            field=models.CharField(max_length=100, null=True),
=======
            field=models.CharField(choices=[('1', 'Espera de pago'), ('2', 'Verificacion de solicitud'), ('3', 'Aprobado'), ('4', 'Rechazado')], max_length=100, null=True),
>>>>>>> backupFriday
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=50)),
                ('usuarioCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.cliente')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='recibo',
            fields=[
                ('idRecibo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPago', models.CharField(max_length=100)),
                ('montoPago', models.FloatField()),
                ('asociacio_idRecibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.asociacion')),
            ],
            options={
                'db_table': 'recibo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='cuentaAportaciones',
            fields=[
                ('idcuentaAportaciones', models.AutoField(primary_key=True, serialize=False)),
                ('cuotaMensual', models.FloatField()),
                ('fechaAportacion', models.CharField(max_length=50)),
                ('aportacionesAsociacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.asociacion')),
            ],
            options={
                'db_table': 'cuentaAportaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='cuentaAhorros',
            fields=[
                ('idCuentaAhorros', models.AutoField(primary_key=True, serialize=False)),
                ('numCuentaAhorros', models.IntegerField()),
                ('saldoActual', models.FloatField()),
                ('movimientoAbonoRetiro', models.FloatField()),
                ('saldoAnterior', models.FloatField()),
                ('ahorrosAsociacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroAsociado.asociacion')),
            ],
            options={
                'db_table': 'cuentaAhorros',
                'managed': True,
            },
        ),
    ]
